#!/bin/bash

SESSION=`cat .session`

if [ $# -ne 0 ]; then
    DAY=$1;
    if [ ! -f src/day${DAY}.txt ]; then
        echo getting day $DAY
        curl -s -b "session=$SESSION" "https://adventofcode.com/2025/day/${DAY}/input" -o ./src/day${DAY}.txt > /dev/null
    else
        echo data for day $DAY already exists
    fi
else
    for i in $(seq 1 12);
    do
        if [ ! -f src/day${i}.txt ] && [ -f src/day${i}.zig ]; then
            ./get $i
        fi
    done
fi

