#!/bin/bash

SESSION=`cat .session`

if [ $# -ne 0 ]; then
    DAY=$1;
    if [ ! -f src/day${DAY}.zig ]; then
        cp template.zig ./src/day${DAY}.zig
        ./get $DAY
        git add ./src/day${DAY}.zig
        git commit -m "starting day $DAY"
    fi
else
    echo "expecting day as argument i.e. ./run 2"
fi

