#!/bin/bash

if [ $# -ne 0 ]; then
    zig run src/day${1}.zig -Doptimize=ReleaseFast
else
    time find src/ -type f | grep -E "day[0-9]+\.zig" | sort | xargs -I {} zig run {} -Doptimize=ReleaseFast
fi
