#!/bin/bash

if [ $# -ne 0 ]; then
    zig run src/day${1}.zig -Doptimize=ReleaseFast
else
    for i in $(seq 1 12);
    do
        if [ -f src/day${i}.zig ]; then
            zig run src/day${i}.zig -Doptimize=ReleaseFast
        fi
    done
fi
