#!/bin/bash

if [ $# -ne 0 ]; then
    zig test src/day${1}.zig
else
    for i in $(seq 1 12);
    do
        if [ -f src/day${i}.zig ]; then
            echo day $i
            zig test src/day${i}.zig
        fi
    done
fi

